<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="HTML Report Example" tests="8" failures="1" errors="1" skipped="1" time="0.15">
  <testsuite name="HTML Report Example" tests="8" failures="1" errors="1" skipped="1" time="0.15" timestamp="2025-03-09T01:41:17">
    <properties>
      <property name="lust_next_version" value="0.7.5"/>
    </properties>
    <testcase name="addition works correctly" classname="Calculator.BasicMath" time="0.001"/>
    <testcase name="subtraction works correctly" classname="Calculator.BasicMath" time="0.001"/>
    <testcase name="multiplication works correctly" classname="Calculator.BasicMath" time="0.001"/>
    <testcase name="division works correctly" classname="Calculator.BasicMath" time="0.001"/>
    <testcase name="division by zero throws error" classname="Calculator.ErrorHandling" time="0.002">
      <failure message="Expected error not thrown" type="AssertionError">Expected function to throw &apos;Division by zero&apos; error
But no error was thrown</failure>
    </testcase>
    <testcase name="square root of negative numbers" classname="Calculator.AdvancedMath" time="0.001">
      <error message="Runtime error in test" type="Error">attempt to call nil value (method &apos;sqrt&apos;)</error>
    </testcase>
    <testcase name="logarithm calculations" classname="Calculator.AdvancedMath" time="0.0">
      <skipped/>
    </testcase>
    <testcase name="rounding behavior" classname="Calculator.AdvancedMath" time="0.001"/>
  </testsuite>
</testsuites>